# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  release:
    types: [ created ]

jobs:
  deploy:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
            ubuntu-20.04-gcc-9,
            windows-2016-msvc-2017,
            macOS-10.15-clang-12.0,
        ]
        python-version: [ 3.6, 3.7, 3.8 ]

        include:
          - name: ubuntu-20.04-gcc-9
            os: ubuntu-20.04
            compiler: gcc
            version: "9"

          - name: windows-2016-msvc-2017
            os: windows-2016
            compiler: cl
            version: "14.16"

          - name: macOS-10.15-clang-12.0
            os: macOS-10.15
            compiler: clang
            version: "12.0"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel bdist_wheel_name
          python setup.py bdist_wheel
          pip install dist/*.whl
          twine upload dist/*
